# Generated by Django 5.2.3 on 2025-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profile/')),
                ('graduate', models.CharField(max_length=100)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('description', models.TextField(max_length=1000)),
                ('work', models.CharField(max_length=100)),
                ('work_experience', models.TextField(max_length=500)),
                ('work_date', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('education_description', models.TextField(max_length=500)),
                ('education_date', models.DateField()),
            ],
        ),
    ]
