# Generated by Django 5.2.3 on 2025-08-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('graduate', models.CharField(blank=True, max_length=100, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('description', models.TextField(blank=True, null=True)),
                ('work', models.CharField(blank=True, max_length=100, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('education_description', models.TextField(blank=True, null=True)),
                ('education_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='posts', to='main.project_tag')),
            ],
        ),
    ]
