# Generated by Django 5.2.3 on 2025-08-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(related_name='posts', to='main.tag')),
            ],
        ),
    ]
