# Generated by Django 5.2.3 on 2025-08-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='work_experience',
            new_name='work_description',
        ),
    ]
