# Generated by Django 5.2.3 on 2025-08-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_work_experience_profile_work_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(blank=True, max_length=100, null=True)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('education_description', models.TextField(blank=True, null=True)),
                ('education_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education_description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_description',
        ),
    ]
