# Generated by Django 5.2.3 on 2025-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_description_project_ful_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_tag',
            name='Tag_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
