# Generated by Django 5.2.3 on 2025-08-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill_remove_profile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='blog', unique=True),
        ),
    ]
