# Generated by Django 5.2.3 on 2025-08-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
