# Generated by Django 5.2.3 on 2025-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture of project/'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='authors',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
