# Generated by Django 5.2.3 on 2025-08-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='ful_description',
            new_name='full_description',
        ),
    ]
