# Generated by Django 5.2.3 on 2025-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_ful_description_blog_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
